# Generated by Django 4.0.6 on 2022-07-29 09:16

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True, max_length=300, null=True)),
                ('author', models.CharField(max_length=100)),
                ('slug', models.SlugField(default=None, editable=False, max_length=255)),
                ('thumbnail', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('tags', models.ManyToManyField(default=None, to='blogs.tags')),
            ],
            options={
                'verbose_name_plural': 'posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
